### ISSUE TITLE
Unable To Install WebScarab 

### ISSUE THREAD

**Issue by AmitPhulera** [OWASP/OWASP-WebScarab#21]
Recently I came to know about WebScarab and  tried to installing it  on my system running Win 8 . It ended up with an Application Error Dialogue Box which said Unable To Start Application. 
When I checked For Details , it said
ExitException[ 3]com.sun.deploy.net.FailedDownloadException: Unable to load resource: http://dawes.za.net/rogan/webscarab/$$codebase/$$name
    at com.sun.javaws.Launcher.updateFinalLaunchDesc(Unknown Source)
    at com.sun.javaws.Launcher.updateFinalLaunchDesc(Unknown Source)
    at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
    at com.sun.javaws.Launcher.prepareToLaunch(Unknown Source)
    at com.sun.javaws.Launcher.launch(Unknown Source)
    at com.sun.javaws.Main.launchApp(Unknown Source)
    at com.sun.javaws.Main.continueInSecureThread(Unknown Source)
    at com.sun.javaws.Main.access$000(Unknown Source)
    at com.sun.javaws.Main$1.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Please Help me Out... 
Thanks In Advance :)
![error](https://cloud.githubusercontent.com/assets/7694243/3425548/1607a866-0007-11e4-82cd-fec64d6cf106.png)

**Comment by thangphamspk** [comment]
Goto [https://sourceforge.net/projects/owasp/files/WebScarab/20070504-1631](url)
and download webscarab-installer-20070504-1631
run webscarab-installer-20070504-1631.jar to deploy.
